
| | |
| :---- | :---- |
| **Professor** | Heidi Getz, Ph.D. [heidi.getz@georgetown.edu](mailto:heidi.getz@georgetown.edu) |
| **Class schedule** | Wednesdays 2-4:30pm |
| **Office hours** | By appointment: [http://calendly.com/hrg2/officehours](http://calendly.com/hrg2/officehours) <br>  Poulton Hall 223 (Linguistics)<br>Building D, Room 154 (Neurology)|
| **Prerequisites** | None |
| **Materials** | Required text: Language Unlimited by David Adger ([Georgetown Bookstore link](https://georgetown.bncollege.com/webapp/wcs/stores/servlet/TBListView?catalogId=10001&storeId=88131&langId=-1&courseXml=\<textbookorder%20xmlns=""\>\<courses\>\<course%20dept="LING"%20num="2370"%20sect="01"%20term="W26"\>\</course\>\</courses\>\</textbookorder\>)); additional readings will be posted on Canvas |

# **Overview**

## **Course description**

Why is human language the way that it is? This course will examine how human language is shaped by “nature” (the biological and genetic characteristics of human beings) as well as by “nurture” (the cultural and social contexts in which humans develop, learn, and use language). We will examine the linguistic structure of natural languages, both spoken and signed, to identify the ways in which languages differ from one another—and the ways in which they do not. To understand how language came to be this way, we will ask which aspects of this (in)variability are present in the rudimentary communication systems developed by Deaf children who grow up without exposure to a natural signed language; in new or emerging human languages (e.g., Nicaraguan Sign Language, Amami Island Sign Language); and in animal communication systems. We will also examine how the process of cultural transmission influences language structure, using evidence from the development of real languages and also from psychological experiments on language evolution in the lab. A major component of the course is our “Grow a Language” project, in which students construct an artificial language and study how the language changes as it is transmitted from one “generation” of learners to the next (a replication of a famous psychological experiment). Through the course, students will gain insight into the deep similarities across languages (including signed languages); the ability to identify and interpret scientific evidence relevant to the nature/nurture question in human cognition; and hands-on experience conducting an experiment in psycholinguistics.

## **Learning goals**

The course is designed to achieve the following learning outcomes:

* Knowledge of how languages are structured  
* Knowledge of the equality of languages and language varieties and commonly held misconceptions about them (especially signed languages)  
* Knowledge of the complexity and underlying systematicity of natural languages  
* Knowledge of the theories and empirical findings relevant to the nature/nurture question in language structure and acquisition  
* Ability to analyze and interpret linguistic and psycholinguistic data  
* Ability to carry out a psycholinguistic research experiment

## **Structure**

The format of class will vary depending on the day. Classes will include a mix of lecture, discussion, and partner/small group work on the “Grow a Language” project (see below).

# **Requirements**

10% 	Attendance  
5%	Preparation and participation  
40%	Homeworks  
45%	Grow a Language project

## **Preparation and participation**

To help you prepare for class, I will ask you to do some reading or to watch a short film/documentary. This preparation is mandatory, not optional. You can demonstrate that you’re prepared by asking questions in class about what you read/watched or by raising a point that was mentioned in the assigned work. 

## **Homework assignments**

There will be occasional short (1-3 page) written assignments due throughout the semester. Details will be provided in class. 

## **Grow a Language project**

Throughout the semester, you will work with one or two classmates to study the evolution of a made-up miniature language. Here’s how it works: You’ll start by making up a list of words for your language, and you’ll give each word a meaning. You’ll set up a psycholinguistic language-learning experiment and ask a friend to participate in the experiment and learn what the words mean. At the end of the experiment, you’ll test your friend to see if they learned the words. Then, you’ll use that friend’s responses on the test to form the list of words that your *next* friend learns from. It’s like a game of telephone. This is a replication of a famous experiment by Dr. Simon Kirby at the University of Edinburgh—we’ll read the study in class. In Prof. Kirby’s original experiments, as the miniature language was transmitted from learner to learner, the language became less arbitrary, and the parts of words started to mean specific things—just like they often do in real languages. In class, you’ll study what happens to your own miniature language and compare it to the original. Through this project, you’ll get hands-on experience running a psycholinguistic experiment and conducting data analysis, and you’ll see how the process of language transmission can shape language structure.

You will receive separate grades for various components of the project:  
5% 	Study files   
15% 	Data analysis  
20% 	Final paper  
5% 	Peer evaluation

# **Course policies**

## **Names**

You can call me by my first name (Heidi) or, if you’re more comfortable using a title, Professor Getz or Dr. Getz. 

To help me learn your name, please consider using [this link](https://www.speakpipe.com/HeidiGetz) to record yourself saying your name the way you’d like me to pronounce it.

## **Attendance**

Attendance is mandatory. Unexplained absences will affect your grade. That said:

* If you know in advance that you won’t be able to make it to a particular class due to a religious holiday, sports conflict, etc., no problem—just let me know ahead of time.  
* If you’re sick and/or contagious, please DO NOT come to class. Email me to let me know you are not well enough to come. I will not ask any follow-up questions, and I will never require you to provide a doctor’s note.

There is no Zoom option for this course. 

## **Extensions**

For some homeworks, it may be possible to request an extension of up to one week. You don’t have to tell me why. You can request an extension for as many assignments as you need to, but you can’t request more than one extension per assignment. Check with about whether extensions are available for a particular assignment as soon as you recognize that you might need one. 

## **Use of AI**

I think that generative AI (Chat GPT, etc.) can be a great tool and that students should learn to use it. However, this course is not the place for you to do that. This course is also not one in which generative AI would do a particularly good job. In any case, I expect you to complete all of your work without the aid of generative AI, unless I specifically say otherwise. In this course, **presenting AI-generated work (including text and ideas) as your own constitutes a violation of academic integrity**. If I suspect that AI was used for an assignment, I will refer the submission to the Honor Council for investigation. This can have enormous consequences for you, including a permanent notation on your transcript or even suspension or dismissal from Georgetown.

It is ok to use basic copy-editing/spell-checking tools like the ones provided by Grammarly, Microsoft Word, and Google Docs.

## **Accommodations**

If you might require an accommodation in this course, you may contact the [Academic Resource Center (ARC)](https://academicsupport.georgetown.edu/). Available accommodations include notetaking assistance, interpreting/CART services, extra time on assignments, or any other accommodation that the ARC deems “reasonable” based on a conversation with you and documentation from the appropriate people (e.g. your doctor). To arrange accommodations (or just to explore this option), email [arc@georgetown.edu](mailto:arc@georgetown.edu) or visit the ARC in-person (Leavey Center, Suite 335, which is accessible from the elevators next to the student credit union, around the corner from the bookstore). There’s more information about this process on [the ARC’s website](https://academicsupport.georgetown.edu/disability/).

Recording course lectures: One possible ARC accommodation is access to special note-taking software. This software allows students to audio-record class, generate a transcription of that recording, and store it alongside other course materials (e.g., lecture slides). When students are approved for this accommodation, they must sign a document agreeing that recordings are for their personal use only, and they are required to delete all recordings at the end of the semester. 

## **Communication**

To promote the highest degree of education possible, we ask each student to respect the opinions, thoughts, and identity of other students and be courteous in the way that you choose to express yourself. We should all be respectful and considerate of all opinions.

## **Religious holidays**

Georgetown University promotes respect for all religions. Any student who is unable to attend classes or to participate in any examination, presentation, or assignment on a given day because of the observance of a major religious holiday or related travel shall be excused and provided with the opportunity to make up, without unreasonable burden, any work that has been missed for this reason and shall not in any other way be penalized for the absence or rescheduled work. Students will remain responsible for all assigned work. Students should notify professors in writing at the beginning of the semester of religious observances that conflict with their classes. The Office of the Provost, in consultation with Campus Ministry and the Registrar, will publish, before classes begin for a given term, a list of major religious holidays likely to affect Georgetown students. This list can be found on the Campus Ministry website, [http://campusministry.georgetown.edu](http://campusministry.georgetown.edu/). The Provost and the Main Campus Executive Faculty encourage faculty to accommodate students whose bona fide religious observances in other ways impede normal participation in a course. Students who cannot be accommodated should discuss the matter with an advising dean.

# **Resources**

## **Sexual Misconduct**

I am committed to supporting survivors of sexual misconduct, including relationship violence, sexual harassment, and sexual assault. **However, university policy also requires me to report any disclosures about sexual misconduct to the Title IX Coordinator, whose role is to coordinate the University’s response to sexual misconduct.** If I report an incident to the Title IX Coordinator, the coordinator would then reach out to you to provide support, resources, and the option to meet. You would not be required to meet with the coordinator. More information about reporting options and resources is available [here](https://sexualassault.georgetown.edu/#_ga=2.84763163.302405512.1597672771-114879328.1580830596).

As an alternative to speaking with me or another mandated reporter, you can reach out for support and assistance to these other fully confidential professional resources:

* Confidential email address for Sexual Assault Response and Prevention (SARP): [sarp@georgetown.edu](mailto:sarp@georgetown.edu)  
* Jen Schweer, MA, LPC, Associate Director of Health Education Services for Sexual Assault Response and Prevention (202) 687-0323 | [jls242@georgetown.edu](mailto:jls242@georgetown.edu)  
* Brittany Egan, MSW, LICSW, CCTP, Staff Clinician and Sexual Assault Services Specialist, Health Education Services (202) 687-0323 | [be200@georgetown.edu](mailto:be200@georgetown.edu)  
* Counseling and Psychiatric Services (CAPS), (202) 687-6985

## **Office of the Student Ombuds (OSO)**

Confidential | Independent | Impartial | Informal

The Office of the Student Ombuds (OSO) serves all undergraduate and graduate students, including SCS and BGE, on the main campus. Consider contacting the Student Ombuds when you want to talk to a caring professional about a University-related issue but don't know where to turn. The OSO is a confidential and safe space that is independent of formal university organizations or structures where students can discuss their concerns, share their experiences, ask questions and explore their options. The student ombuds can help you problem-solve, identify your goals, and empower you to think through ways to navigate complex situations. Some reasons for you to visit the office may be to address academic concerns, clarify administrative policies, discuss interpersonal conflicts, seek coaching, mediation or facilitation to handle a sensitive situation, advise you on the process to file a formal complaint if you are experiencing bias, harassment, bullying or other forms of intimidation, identify other appropriate campus resources, and allow you to safely express your frustrations and concerns.

Request an in-person or zoom appointment with the Student Ombuds by writing studentombuds@georgetown.edu  or calling 202-784-1081. The OSO is located in Room 207 of the Reiss Building (across from Arrupe Hall). Find more information at [http://studentombuds.georgetown.edu](http://studentombuds.georgetown.edu/).

## **Learning Resources**

Georgetown offers a host of [learning resources](http://scs.georgetown.edu/academic-affairs/resources/) to its students. Two that you might find particularly helpful in this course are the [Writing Center](https://writingcenter.georgetown.edu/) and [Refworks](http://guides.library.georgetown.edu/refworks).

* [The Writing Center](https://writingcenter.georgetown.edu/) offers peer tutoring by trained graduate and undergraduate students who can assist you at any point in the writing process. They help at any stage of your writing process, from brainstorming to revision. Tutors can offer advice on thesis development, use of evidence, organization, flow, sentence structure, grammar, and more. The Writing Center will not proofread or edit papers; rather, they will help to improve your proofreading and editing skills to become a better writer. Appointments can be booked online through their website.  
* [Refworks](http://guides.library.georgetown.edu/refworks) is an online research management tool that aids in organizing, storing, and presenting citation sources for papers and projects.

# **Disability Studies Event Series**

This course is cross-listed with Georgetown’s [Disability Studies program](https://disabilitystudies.georgetown.edu/). I encourage you to attend these events:

Monday, Jan 12, 4:00pm \- 5:30pm, Mortara Center for International Studies, professor  **Emily Mendenhall discusses her new book, Invisible Illness: A History, from Hysteria to Long Covid**, with Dr. Amy Kenny, Professor Lakshmi Krishnan, and Professor Libbie Rifkin

Monday, February 2nd, 6-7pm, Healey Family Student Center Social Room, author **Rachel Kolb discusses her book, *Articulate: A Deaf Memoir of Voice,*** ASL interpreted.

Tuesday, April 14, 5-6:15pm, McShain Large, McCarthy Hall, UNC Charlotte professor **Damien Williams discusses disability and AI,**  ASL interpreted.